In [1]:
import numpy as np

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [10]:
a=np.ones((3,2))

In [11]:
np.ravel(a)

array([1., 1., 1., 1., 1., 1.])

In [16]:
np.arange(8).reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [17]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
np.nonzero([0,0,0,0,0,3])

(array([5], dtype=int64),)

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.random((5,3))

array([[0.10561567, 0.08541226, 0.28014944],
       [0.71202835, 0.65930738, 0.54863701],
       [0.43976548, 0.90198493, 0.28171278],
       [0.06622367, 0.8036149 , 0.67166022],
       [0.99722739, 0.60689028, 0.90580697]])

In [27]:
A=np.ones((5,5))

In [28]:
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
A[1:-1,1:-1]=0

In [30]:
A

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
A=['a','b','c','d','d','d','e','a','b','f','g','g','h']
  

IndentationError: unexpected indent (<ipython-input-40-b66714d0457a>, line 2)

In [43]:
B=A.copy()
b=set(B)
Dict1={}
for i in A:
    c=A.count(i)
    Dict1[i]=c

In [44]:
Dict1

{'a': 2, 'b': 2, 'c': 1, 'd': 3, 'e': 1, 'f': 1, 'g': 2, 'h': 1}

In [45]:
help(np.where)

Help on built-in function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called whe